// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chaing_ordertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chaing_ordertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202311011820491_chaing_ordertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
