// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_Isfeatured_ImageURL_in_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Isfeatured_ImageURL_in_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202305040510084_added_Isfeatured_ImageURL_in_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
