// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class chanignOrderTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chanignOrderTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202311011830528_chanignOrderTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
